
//  console.log(5+3);

// let x = 9.234;
// y = x.toPrecision(9);
// console.log(y);

// let x = 3;
// let y = 4;

// console.log(x+y);

// var x = "5";
// var y = 4;
// console.log(x+y);

// let text="HEllo world";
// let result=text.match(/World/i);
// console.log(result);
// Not case sensitive

// let text="HEllo world";
// let result=text.match(/World/g);
// console.log(result);

// let text="HEllo world";
// let result=text.match(/World/gi);
// console.log(result);

// function hi(){
//     console.log("Hi Everyone")
// }

// hi();

// function click()
// {    
//     var a,b,c;
//      a = 10;
//      b = 20;
//      c = a + b;
//      console.log(c);
// }
// click();
/*
function add(num1, num2) {
    return num1 + num2
  }

  const num1 = 12
  const num2 = 23
  console.log(add(num1, num2))
*/

// Loop

// var n = 5;

// for (let i= 1; i<= n; i++){
//   console.log("I love S");
// }

// const n = 10;

// for (let i = 1; i <= n; i++) {
//   console.log(i);
// }

let sum = 0;
let n = 10;

for (i = 1; i<=n; i++){
    sum+=i;
}
console.log(sum);